services:
  - type: web
    name: contentready-brat-render
    runtime: python
    plan: standard
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: WHISPER_MODEL
        value: small
      - key: WHISPER_DEVICE
        value: cpu
      - key: WHISPER_COMPUTE_TYPE
        value: int8
